web:
    build: .
    dockerfile: web.dockerfile
    ports:
        - 8080:80
    volumes:
        - ./web:/web
        - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - node
node:
    build: .
    dockerfile: node.dockerfile
    volumes:
        - ./web/server:/app
    links:
        - db:postgres_db
db:
    build: .
    dockerfile: db.dockerfile
#    volumes:
#        - ./db:/var/lib/postgresql
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=postgis
        - POSTGRES_PASS=postpass
        - ALLOW_IP_RANGE=0.0.0.0/0
